"""add table payments

Revision ID: d1c643841bdf
Revises: d46dc74b238c
Create Date: 2023-04-07 15:18:23.657689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1c643841bdf'
down_revision = 'd46dc74b238c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='платежи'
    )
    op.alter_column('channel_client', 'channel_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_client', 'channel_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('payments')
    # ### end Alembic commands ###
